{{- if .Values.openshift -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "kogito-app.fullname" . }}
  labels:
    {{- include "kogito-app.labels" . | nindent 4 }}
spec:
  port:
    targetPort: {{ .Values.service.targetPort }}
  to:
    kind: Service
    name: {{ include "kogito-app.fullname" . }}
{{- end }}
